import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional

SHADER_DIR = Path("Shaders")
SPV_DIR = SHADER_DIR / "spv"
MSL_DIR = SHADER_DIR / "msl"
BUILD_DIR = SHADER_DIR / "Build"

GRAPHICS_SHADERS = [
    ("SurfaceForward", "vert", "frag"),
    ("SkinnedForward", "vert", "frag"),
    ("SurfaceDepthOnly", "vert", "frag"),
    ("SkinnedDepthOnly", "vert", "frag"),
    ("LineDebug", "vert", "frag"),
    ("Outline", "vert", "frag"),
    ("UI/Slug", "vert", "frag"),
    ("UI/UIShape", "vert", "frag"),
    ("UI/UIImage", "vert", "frag"),
    ("Shadow/SurfaceShadowDepthOnly", "vert", "frag"),
    ("Shadow/SkinnedShadowDepthOnly", "vert", "frag"),
    ("Shadow/SurfacePointShadowDepthOnly", "vert", "frag"),
    ("Shadow/SkinnedPointShadowDepthOnly", "vert", "frag"),
    ("TerrainForward", "vert", "frag"),
    ("TerrainDepthOnly", "vert", "frag"),
    ("TerrainChunk", "vert", "frag"),
    ("Grass", "vert", "frag"),
]

EXTRA_GRAPHICS_SHADERS = [
    ("UI/Slug", "Slug2DVert", "vert2d", "vs_6_6"),
    ("TerrainDepthOnly", "TerrainWireFrag", "wireFrag", "ps_6_6"),
    ("Shadow/SurfaceSpotShadowDepthOnly", "Shadow/SurfaceSpotShadowDepthOnlyVert", "vert", "vs_6_6"),
    ("Shadow/SkinnedSpotShadowDepthOnly", "Shadow/SkinnedSpotShadowDepthOnlyVert", "vert", "vs_6_6"),
]

COMPUTE_SHADERS = [
    ("TexturePageCopyRGBA", "main"),
    ("TexturePageCopyRG", "main"),
    ("UI/ColorPickCompute", "main"),
    ("ReconstructNormalCompute", "main"),
    ("PreProcessing/BuildLightGridCompute", "main"),
    ("Animation/AnimationCompute", "main"),
    ("Animation/AnimateVertices", "main"),
    ("PreProcessing/CullDrawArgsCompute", "main"),
    ("PreProcessing/HiZBuildCompute", "main"),
    ("PreProcessing/HiZDownscaleSPDCompute", "main"),
    ("PostProcessing/TonemapCompute", "main"),
    ("PostProcessing/BloomDownsampleSPDCompute", "main"),
    ("PostProcessing/BloomUpsampleCompute", "main"),
    ("PostProcessing/HBAOCompute", "main"),
    ("PostProcessing/HBAOBlurCompute", "main"),
    ("PostProcessing/ContactShadowsCompute", "main"),
    ("PostProcessing/MLAAEdgeMaskCompute", "main"),
    ("PostProcessing/MLAALineLengthCompute", "main"),
    ("PostProcessing/MLAABlendCompute", "main"),
]

MSL_FIXUPS = {
    "SurfaceFrag": [
        ("NormalPages [[texture(0)]]", "NormalPages [[texture(1)]]"),
    ],
    "TerrainForwardFrag": [
        ("NormalLayers [[texture(0)]]", "NormalLayers [[texture(1)]]"),
    ],
    "Animation/AnimateVertices": [
        ("sSparseToDense [[buffer(7)]]", "sSparseToDense [[buffer(6)]]"),
    ],
}


def host_default_format() -> str:
    if platform.system() == "Darwin":
        return "msl"

    return "spv"


def find_tool(names: List[str]) -> Optional[str]:
    for name in names:
        if os.sep in name or (os.altsep and os.altsep in name):
            path = Path(name)

            if path.exists():
                return str(path)

            continue

        found = shutil.which(name)

        if found:
            return found

    return None


def find_dxc() -> Optional[str]:
    return find_tool([
        str(BUILD_DIR / "dxc.exe"),
        str(BUILD_DIR / "dxc"),
        "dxc",
    ])


def find_shadercross() -> Optional[str]:
    env_path = os.environ.get("SHADERCROSS")
    names = []

    if env_path:
        names.append(env_path)

    names += [
        str(BUILD_DIR / "shadercross.exe"),
        str(BUILD_DIR / "shadercross"),
        "shadercross",
    ]

    return find_tool(names)


def run_cmd(args: List[str], error_msg: str) -> None:
    print(" ".join(str(a) for a in args), flush=True)

    result = subprocess.run(args)

    if result.returncode != 0:
        print(error_msg)
        sys.exit(result.returncode)


def require_file(path: Path) -> None:
    if not path.exists():
        print("[ERROR] Missing file: {}".format(path))
        sys.exit(1)


def output_var_name(out_name: str, fmt: str) -> str:
    safe = "".join(ch if ch.isalnum() else "_" for ch in out_name)
    return "Shaders_{}_{}".format(safe, fmt)


def write_c_header(input_path: Path, header_path: Path, out_name: str, fmt: str) -> None:
    data = input_path.read_bytes()
    name = output_var_name(out_name, fmt)

    header_path.parent.mkdir(parents=True, exist_ok=True)

    with header_path.open("w", newline="\n") as f:
        f.write("/* Generated by Shaders/CompileShaders.py, do not edit manually */\n\n")
        f.write("const unsigned int {}_size = {};\n".format(name, len(data)))
        f.write("const unsigned char {}[{}] = {{\n".format(name, len(data)))

        for offset in range(0, len(data), 16):
            chunk = data[offset:offset + 16]
            values = ", ".join("0x{:02X}".format(byte) for byte in chunk)
            f.write("    {},\n".format(values))

        f.write("};\n")


def patch_msl_bindings(shader_path: Path, out_name: str) -> None:
    fixups = MSL_FIXUPS.get(out_name)

    if not fixups:
        return

    source = shader_path.read_text()

    for old, new in fixups:
        if old not in source:
            print("[ERROR] Missing MSL fixup target in {}: {}".format(shader_path, old))
            sys.exit(1)

        source = source.replace(old, new)

    shader_path.write_text(source, newline="\n")


def shader_stage(target: str) -> str:
    if target.startswith("vs_"):
        return "vertex"

    if target.startswith("ps_"):
        return "fragment"

    return "compute"


def compile_spv_with_dxc(
    dxc: str,
    hlsl: Path,
    output: Path,
    entry: str,
    target: str,
) -> None:
    run_cmd(
        [
            dxc,
            "-spirv",
            "-fspv-target-env=vulkan1.1",
            "-T", target,
            "-E", entry,
            "-enable-16bit-types",
            "-I", str(SHADER_DIR),
            "-I", str(hlsl.parent),
            str(hlsl),
            "-Fo", str(output),
        ],
        "[ERROR] Failed to compile {} entry {}".format(hlsl, entry),
    )


def compile_with_shadercross(
    shadercross: str,
    hlsl: Path,
    output: Path,
    entry: str,
    target: str,
    fmt: str,
) -> None:
    run_cmd(
        [
            shadercross,
            "-s", "HLSL",
            "-d", "MSL" if fmt == "msl" else "SPIRV",
            "-t", shader_stage(target),
            "-e", entry,
            "-I", str(hlsl.parent),
            "-o", str(output),
            str(hlsl),
        ],
        "[ERROR] Failed to compile {} entry {}".format(hlsl, entry),
    )


def compile_shader(
    src_name: str,
    out_name: str,
    entry: str,
    target: str,
    fmt: str,
    dxc: Optional[str],
    shadercross: Optional[str],
) -> bool:
    hlsl = SHADER_DIR / "{}.hlsl".format(src_name)
    out_dir = MSL_DIR if fmt == "msl" else SPV_DIR
    shader = SHADER_DIR / "{}.{}".format(out_name, fmt)
    header = out_dir / "{}.{}.h".format(out_name, fmt)

    require_file(hlsl)

    script = Path(__file__)
    # [here]
    if header.exists() and header.stat().st_mtime > max(hlsl.stat().st_mtime, script.stat().st_mtime):
        return False

    print("Compiling {}.hlsl entry {} -> {}.{}...".format(src_name, entry, out_name, fmt))

    shader.parent.mkdir(parents=True, exist_ok=True)
    header.parent.mkdir(parents=True, exist_ok=True)

    if fmt == "msl":
        if not shadercross:
            print("[ERROR] shadercross is required for macOS MSL shader compilation.")
            print("Install SDL_shadercross and ensure `shadercross` is on PATH, or set SHADERCROSS=/path/to/shadercross.")
            sys.exit(1)

        compile_with_shadercross(shadercross, hlsl, shader, entry, target, fmt)
        patch_msl_bindings(shader, out_name)

    elif shadercross:
        compile_with_shadercross(shadercross, hlsl, shader, entry, target, fmt)

    elif dxc:
        compile_spv_with_dxc(dxc, hlsl, shader, entry, target)

    else:
        print("[ERROR] Missing shader compiler.")
        print("Install `dxc` or SDL_shadercross, or place dxc/dxc.exe in Shaders/Build.")
        sys.exit(1)

    write_c_header(shader, header, out_name, fmt)
    shader.unlink()

    return True


def compile_all_shaders(fmt: str) -> None:
    dxc = find_dxc()
    shadercross = find_shadercross()

    if dxc:
        print("Using dxc: {}".format(dxc))

    if shadercross:
        print("Using shadercross: {}".format(shadercross))

    out_dir = MSL_DIR if fmt == "msl" else SPV_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Processing Graphics Shaders...")

    graphics_compiled = 0
    graphics_skipped = 0

    for name, vs_entry, ps_entry in GRAPHICS_SHADERS:
        if compile_shader(name, "{}Vert".format(name), vs_entry, "vs_6_6", fmt, dxc, shadercross):
            graphics_compiled += 1
        else:
            graphics_skipped += 1

        if compile_shader(name, "{}Frag".format(name), ps_entry, "ps_6_6", fmt, dxc, shadercross):
            graphics_compiled += 1
        else:
            graphics_skipped += 1

    for name, out_name, entry, target in EXTRA_GRAPHICS_SHADERS:
        if compile_shader(name, out_name, entry, target, fmt, dxc, shadercross):
            graphics_compiled += 1
        else:
            graphics_skipped += 1

    print_shader_summary("Graphics", graphics_compiled, graphics_skipped)

    print("\nProcessing Compute Shaders...")

    compute_compiled = 0
    compute_skipped = 0

    for name, entry in COMPUTE_SHADERS:
        if compile_shader(name, name, entry, "cs_6_6", fmt, dxc, shadercross):
            compute_compiled += 1
        else:
            compute_skipped += 1

    print_shader_summary("Compute", compute_compiled, compute_skipped)


def print_shader_summary(label: str, compiled: int, skipped: int) -> None:
    total = compiled + skipped

    if skipped == total:
        print("{}: all {} shaders up to date.".format(label, total))
    else:
        print("{}: compiled {}, skipped {}.".format(label, compiled, skipped))


def main() -> int:
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--format",
        choices=["spv", "msl"],
        default=host_default_format(),
        help="Output shader header format. Defaults to msl on macOS, spv elsewhere.",
    )

    args = parser.parse_args()

    compile_all_shaders(args.format)

    print("\nSUCCESS: All shaders processed.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
